# Setup
title:            Opti.ml
tagline:          ''
description:      ''
url:              https://junyoungpark.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Junyoung Park'
  url:            github.com/junyoungpark

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
